### PR TITLE
Frontend with materializecss setup

### PR DESCRIPTION
**Pull request by mitas1**
This MR contains:
- sass and sass:watch gulp tasks for processing sass files, it will inject static files during the development
- webpack-dev-server gulp task just for starting webpack-dev-server
- wepback bundling of javascript assets, webpack-dev-server will serve them and provides a hot module reloading
- materalizecss 1.0.0-alpha.1 - we are using alpha version so we can use this documentation: http://next.materializecss.com/
- one dummy template and view for demosntration purposes

### CODE REVIEW

**Comment by mskrip** [comment]
```sh
python manage.py runserver
>>> Starting gulp
>>> gulp process on pid 6689
/bin/sh: gulp: command not found
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mskrip/Documents/school/wtam/building-log/.venv/lib/python3.6/site-packages/django_gulp/management/commands/runserver.py", line 124, in start_gulp
    raise CommandError('gulp exited unexpectedly')
django.core.management.base.CommandError: gulp exited unexpectedly

>>> Killing pid 6688
>>> Exiting
make: *** [Makefile:24: run] Error 1
```

**Comment by mskrip** [comment]
Also, if I run `make install` the `package-lock.json` gets modified. Do we need to verse that?

**Comment by mitas1** [comment]
I've updated README.md. You need to install `gulp-cli` globally. And yes, we want to verse `package-lock.json`. More explanation is [here](https://docs.npmjs.com/files/package-lock.json). I probably forgot to update dependecies. Try to do the following commands:
` $ rm package-lock.json`
` $ rm -r node_modules `
`$ npm install`
` $ git diff `
Is diff still too big?

**Comment by mitas1** [comment]
I've added `sass` task to gulp default tasks. So for now, it should compile sass files after `make run` command. And @mskrip, as we discussed in our team mac os is predominant, so we are going to use `package-lock.json` generated on mac OS X :)

**Comment by mskrip** [comment]
works and LGTM

**Pull request merged**
