### PR TITLE
Login view

### LINKED ISSUE #17: Login view

### PR DESCRIPTION
**Pull request by mitas1**
Contains loginview and simple app template.

Close #17

### CODE REVIEW

**Comment by mskrip** [comment]
Mobile version seems a bit too small
image

**Comment by mskrip** [comment]
Also on my phone (not in chrome dev tools), the login help labels do not dodge the text input when focused

image

**Comment by mitas1** [comment]
I've added viewport meta tag now it should looks good in mobile devices. And the issue with login help labels is probably caused by the unreachable assets served by webpack-dev-server, because it works in chrome dev tools.

**Comment by mskrip** [comment]
OK, looks awesome. The menu on my phone is not working but I assume it's got also to do with unreachable assets (works on chrome dev tools). Anyways **LGTM** for me

**Comment by slama6** [comment]
LGTM for me too...

**Pull request merged**
